[versions]
java = "25"
minecraft = "1.21.10"
paperweight = "2.0.0-beta.19"
run-paper = "3.0.2"
shadow = "9.2.2"
protobuf-gradle-plugin = "0.9.5"
protoc = "4.29.0"
lombok = "1.18.42"
gson = "2.13.2"
okhttp = "4.12.0"
caffeine = "3.2.3"
fastutil = "8.2.1"
guice = "7.0.0"
annotations = "26.0.2"
jnats = "2.24.0"
junit-bom = "5.10.0"
cloud-paper = "2.0.0-beta.10"
reflections = "0.10.2"
packetevents-spigot = "2.10.1"
redisson = "3.52.0"
sonarqube = "7.1.0.6387"
checkstyle = "12.1.2"
editorconfig = "0.1.0"
stylecheck = "0.2.1"

[libraries]
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version.ref = "caffeine" }
caffeine-guava = { module = "com.github.ben-manes.caffeine:guava", version.ref = "caffeine" }
caffeine-jcache = { module = "com.github.ben-manes.caffeine:jcache", version.ref = "caffeine" }
fastutil = { module = "it.unimi.dsi:fastutil", version.ref = "fastutil" }
guice = { module = "com.google.inject:guice", version.ref = "guice" }
annotations = { module = "org.jetbrains:annotations", version.ref = "annotations" }
jnats = { module = "io.nats:jnats", version.ref = "jnats" }
protobuf-java = { module = "com.google.protobuf:protobuf-java", version.strictly = "4.29.0", version.prefer = "4.33.1" }
protobuf-protoc = { module = "com.google.protobuf:protoc", version.ref = "protoc" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit-bom" }
cloud-paper = { module = "org.incendo:cloud-paper", version.ref = "cloud-paper" }
reflections = { module = "org.reflections:reflections", version.ref = "reflections" }
packetevents-spigot = { module = "com.github.retrooper:packetevents-spigot", version.ref = "packetevents-spigot" }
redisson = { module = "org.redisson:redisson", version.ref = "redisson" }
stylecheck = { module = "ca.stellardrift:stylecheck", version.ref = "stylecheck" }

[plugins]
protobuf = { id = "com.google.protobuf", version.ref = "protobuf-gradle-plugin" }
paperweight = { id = "io.papermc.paperweight.userdev", version.ref = "paperweight" }
run-paper = { id = "xyz.jpenilla.run-paper", version.ref = "run-paper" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
sonarqube = { id = "org.sonarqube", version.ref = "sonarqube" }
editorconfig = { id = "org.ec4j.editorconfig", version.ref = "editorconfig" }
