spring:
  application:
    name: "PrivateAPI"
  data:
    mongodb:
      uri: ${PRIVATE_API_MONGODB_URI}
    redis:
      host: ${PRIVATE_API_REDIS_HOST}
      port: ${PRIVATE_API_REDIS_PORT}
    cache:
      type: redis
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: "always"
