on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  checkstyle:
    name: runner / checkstyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Download stylecheck
        run: |
          wget -q "https://repo1.maven.org/maven2/ca/stellardrift/stylecheck/0.2.1/stylecheck-0.2.1.jar" \
            -O stylecheck.jar
      - uses: dbelyaev/action-checkstyle@cbb61fa05565e0e47512a34f5127bd2318f56d9d
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          fail_level: warning
          checkstyle_version: "12.1.2"
          checkstyle_config: config/checkstyle/checkstyle.xml
          properties_file: config/checkstyle/checkstyle.properties
          reviewdog_flags: "-class-path ./stylecheck.jar"
  checkstyle-v2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Download stylecheck module
        run: |
          wget -q https://repo1.maven.org/maven2/ca/stellardrift/stylecheck/0.2.1/stylecheck-0.2.1.jar \
            -O stylecheck.jar
      - name: Run Checkstyle
        uses: nacier/checkstyle-action@v2
        with:
          checkstyle_version: "12.1.2"
          config: "config/checkstyle/checkstyle.xml"
          classpath: "stylecheck.jar"
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}
